### PR TITLE
minor documentation cleanups

### PR DESCRIPTION
**Pull request by bradh**
Provides minor spelling fixes, and some format changes (markdown lint fixes) in the README.md.

### CODE REVIEW

**Comment by rjhowell44** [comment]
@bradh thanks so much for this, I really appreciate it!  I've merged your updates into the v0.19.alpha branch to be included in the next release.

Please don't hesitate to make suggestions, report issues, or provide feedback at anytime. 
Thanks again,
Robert

**Comment by bradh** [comment]
Would you prefer PRs against the next alpha? That is, is master the "release" branch?

**Comment by rjhowell44** [comment]
Yes, please... sorry that I don't have this process written up yet.  I like to keep the master as the last/current release and work off of the "next" release branch.

**Comment by rjhowell44** [comment]
@bradh I wanted to invite you to our [discord server](https://discord.gg/MJvY9jjpAK) ... an informal place to chat, ask questions, discuss ideas,  etc.  And thanks again for the pull request!

**Pull request merged**
