### PR TITLE
Updated VSCode tasks and launch configurations

### PR DESCRIPTION
**Pull request by jlerasmus**

### CODE REVIEW

**Comment by rjhowell44** [comment]
@youngjae-avikus just fyi

**Comment by jlerasmus** [comment]
@rjhowell44 Just a suggestion, but I would vote for merging all PRs using a merge commit, instead of squashing or rebasing the commit as this gives a more detailed history of changes.

There are different opinions on this, but I have just found it better to have a merge commit for PRs, to show the full branching and commit history.  For example, some detail on the line-crossing changes between the original and addition of previous-trace was lost when the v0.24.alpha branch was merged.

For reference: https://myst729.github.io/posts/2019/on-merging-pull-requests/

Repo merge options can be specified https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests

**Comment by rjhowell44** [comment]
@jlerasmus my practice of squashing merges is just based on previous projects.... it has always been requirement.  I can change the process if you and others prefer though.

**Comment by jlerasmus** [comment]
@rjhowell44 the request is just from my experience working in large teams using git, but it is your decision.  Merge commits were being used up to v0.08.alpha.

Maybe an option is to squash merges for PRs from feature branches (e.g. line-crossing) to the current develop branch (e.g. v0.25.alpha) to shorten detail for feature branch commits, but to have a merge commit for PRs from the current develop branch (e.g. v.025.alpha) to master.  This will at least keep feature and bugfix history intact.

Maybe you can bring this up on Discord if you want too, but I will rest with your decision.

**Comment by rjhowell44** [comment]
My apologies @jlerasmus, I thought I had responded earlier, but apparently not.  And no problem on dropping the squashes.

**Pull request merged**
