### PR TITLE
ACE-25: 

### PR DESCRIPTION
**Pull request by jksison**
added spdlog library and logic to replace the DSL's default logger.

### CODE REVIEW

**Comment by rjhowell44** [comment]
@jksison I appreciate your interest in DSL and all your work here.  It looks very interesting!  Please, give me a day to review and digest this and I'll get back to you with some comments tomorrow.  Thanks again.

**Comment by rjhowell44** [comment]
@jksison I'm going to need a little more time with this,

**Comment by jksison** [comment]
Thank you sir! You may ignore the merge. It's only an idea.

**Comment by rjhowell44** [comment]
@jksison thanks again for your interest in improving DSL and my apologies again for the slow response.

First, for pull requests, please refer to the section [DSL Branching Workflow](https://github.com/prominenceai/deepstream-services-library#dsl-branching-workflow). All changes and pull requests need to be made to the active release branch which is now [v0.01.beta](https://github.com/prominenceai/deepstream-services-library/tree/v0.01.beta). v0.01beta is already 20 commits ahead of master and will be merged into master only when all objectives for the release have be met. 

Also, each of your enhancements (fixed-sink, spd logging, custom sources, etc) would need to be separate pull requests. Each would need to be reviewed and pulled in separately. 

---

For your logging changes... Keep in mind that DslApi.h is a public static C api.  All services in this file get mapped to Python, HTTP, RUST (soon), etc.  There can be no includes in this file. We cannot have
```c
#include "spdlog/spdlog.h"
```
All parameters used must be of simple C POD types.  This is required for the mapping to other languages.  So we cannot have 
```c
DslReturnType dsl_setup_sdp_logger(std::shared_ptr<spdlog::logger> logger);
```

Also, any service added to DslApi.h/cpp must also be added to dsl.py as well.
Also, we would need API and Unit test coverage plus API reference documentation for all new work.  I can help with this.

--- 

I like your custom source idea, however, I think it should support multiple custom elements similar to the custom component. 

---

Can I suggest that you start with just a pull request for the Sink fix on v0.01 beta branch and then we can look at the other items after that? 

Thanks again,
Robert.

**Comment by jksison** [comment]
Thank you, Robert, for your helpful feedback. I'll be sure to incorporate it.

**Pull request closed without merging**
